version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - aws-s3/sync:
          from: script
          to: AWS_S3_DESTINATION_BLUE
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
      - run: script/ci
