#!/bin/sh

set -e

TIMESTAMP=`date +%Y-%m-%d-%H-%M-%S`

curl -X PUT -i https://api.github.com/repos/notjasonrudolph-inc-for-unserious-works/canary/contents/coalmine/${TIMESTAMP}.md \
  -H "Content-Type: application/json" \
  -H "Authorization: token ${GITHUB_TOKEN}" \
  -d "{
        \"message\": \"🐤 ${TIMESTAMP}\",
        \"content\": \"8J+QpAo=\n\",
        \"branch\": \"canary\"
      }"
