name: Canary

on:
  push:
  pull_request:
  schedule:
    - cron: '42 * * * *'

jobs:
  dispatch-canary:
    runs-on: ubuntu-latest
    steps:
    - run: env | grep ^GITHUB_ | sort
    - uses: actions/checkout@v1
    - name: Create commit in canary repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: script/create-canary-commit
